my_comment = "this iS my first Short coMment"
print('my_comment=                          -> ',my_comment)
print('len(my_comment)                      -> ', len(my_comment))
print("my_comment.replace('short', 'long')  -> ", my_comment.replace('Short', 'long'))
print("my_comment.capitalize()              -> ", my_comment.capitalize())
print("my_comment.isupper()                 -> ", my_comment.isupper())
print("my_comment.lower()                   -> ", my_comment.lower())
print("my_comment.upper()                   -> ", my_comment.upper())
print("my_comment.split()                   -> ", my_comment.split())
print("my_comment.split()                   -> ", my_comment.split(sep='s'))
print("my_comment.splitlines()              -> ", my_comment.splitlines())
print("my_comment.strip('ment')             -> ", my_comment.strip('ment'))
print("my_comment.removeprefix('this')      -> ", my_comment.removeprefix('this'))
print("my_comment.removesuffix('coMment')   -> ", my_comment.removesuffix('coMment'))
print("my_comment.title()                   -> ", my_comment.title())
print("my_comment.zfill(3)                  -> ", my_comment.zfill(3))
print("my_comment.swapcase()                -> ", my_comment.swapcase())
print("my_comment.join()                    -> ", my_comment.join('123'))
print("my_comment.index('Short')            -> ", my_comment.index('Short'))
print("my_comment.isdecimal()               -> ", my_comment.isdecimal())
print("my_comment.isdigit()                 -> ", my_comment.isdigit())
print("my_comment.isnumeric()               -> ", my_comment.isnumeric())
print("my_comment.count(' ')                -> ", my_comment.count(' '))
print("my_comment.count('is')               -> ", my_comment.count('is'))
print('my_comment[0]                        -> ', my_comment[0])
print('my_comment[2:7]                      -> ', my_comment[2:7])
print('my_comment[-1]                       -> ', my_comment[-1])
print('my_comment[-7]                       -> ', my_comment[-7])
print('my_comment[8:]                       -> ', my_comment[8:])
print('my_comment[:5]                       -> ', my_comment[:5])
